name = "agile-epic-tool"
compatibility_date = "2024-01-01"
main = "dist/index.js"

[site]
bucket = "./public"

#[vars]
#ENVIRONMENT = "development"

# Only include these if you're using custom KV namespaces
# [[kv_namespaces]]
# binding = "__STATIC_CONTENT"
# id = "your-id-here"

# [[kv_namespaces]]
# binding = "__STATIC_CONTENT_MANIFEST"
# id = "your-manifest-id-here"